### ISSUE TITLE
Occasionally stops receiving messages

### ISSUE THREAD

**Issue by cvincent** [tulir/mautrix-facebook#45]
I've been successfully running this bridge for a few weeks now, it's very fully featured and the most solid bridge I've used so far! However, I noticed that after a while (maybe a day or so, not sure) I stop receiving new messages. I'm still able to send replies, but replies from friends don't come through. Once I restart the docker image, I'm able to receive messages again.

For the time being, I've added a systemd time to restart the docker container each night:

```
# /usr/lib/systemd/system/restart-mautrix-facebook.service
[Unit]
Description=Restart Facebook Matrix bridge so it reconnects
 
[Service]
Type=simple
ExecStart=docker restart mautrix-facebook
Restart=no
```

```
# /usr/lib/systemd/system/restart-mautrix-facebook.timer
[Unit]
Description=Restart Facebook Matrix bridge so it reconnects

[Timer]                
OnCalendar=*-*-* 03:00:00
RandomizedDelaySec=7200

[Install]
WantedBy=timers.target
```

I only added the timer last night, so I can't be sure yet if this is frequent enough. In any case, this is a hacky stopgap to keep it working until the root cause is found.

**Comment by ericmigi** [comment]
any logs from the bridge after it fails?

**Comment by cvincent** [comment]
Nothing out of the ordinary that I saw, just continuous presence `PUT` pings.

**Comment by cvincent** [comment]
Maybe what I'll do is disable my timer for now, wait for it to fail again, and see if I can get some more useful diagnostics. For example, have someone send me a message and see what shows in the logs, if anything.

**Comment by antonok-edm** [comment]
FWIW I've done this as well and found 1 day is actually too infrequent. I just went for once an hour at that point and I don't think I've missed anything since, but it probably doesn't need to be *quite* that often.

**Comment by cvincent** [comment]
Good to know I'm not the only one experiencing this. That said, so far I'm up 2 days, still receiving messages. Will report back when I get more info.

**Comment by cvincent** [comment]
Up 4 days now. I did receive a couple messages that didn't come through the bridge, and I thought maybe it was time to restart. But actually regular messages are still coming through. The two that didn't come through were attachments: one was a video and the other was a link. So at this point, I'm wondering if that's what I had seen before, but had mistaken it for being unable to receive messages in general. Then again, last time it stopped I think I had someone send me a regular message to be sure, but I don't remember. Maybe @antonok-edm is more sure?

I'm going to keep running the bridge until I experience messages not coming through, and I'm watching the logs. In the meantime, are videos or links a known issue? I saved the log output when that happened and can share it if that'd be helpful, after I scrub personal details from it.

**Comment by ADIX7** [comment]
I had the same issue and I'm sure regular messages were lost. Currently I'm also running it, waiting for to fail again.

**Comment by antonok-edm** [comment]
@cvincent I've definitely lost regular messages as a result, and I couldn't find anything particularly useful in the logs when that happened, either.

**Comment by cvincent** [comment]
After 7 days up, I finally got a message that didn't come through on Matrix. I went through the logs, and there was nothing for the message. I did, however, see log entries for when the user started and stopped typing. Strange!

**Comment by ADIX7** [comment]
It failed tomorrow for me too. Also nothing in the logs.

**Comment by satcom886** [comment]
This happened to me once as well... But it didn't happen since I restarted the bridge.

**Comment by Samonitari** [comment]
I also have this issue. Even with regular messages, regardless of room size.

@cvincent Big :+1: for non-cronjob restart timer!

**Comment by sephamorr** [comment]
Have this issue too, this is what has been showing up in my debug logs:

`[2020-03-15 12:36:58,259] [DEBUG@hbmqtt.mqtt.protocol.handler] Scheduling Ping
[2020-03-15 12:36:58,260] [DEBUG@hbmqtt.client.plugins.packet_logger_plugin] mqttwsclient -out-> PingReqPacket(ts=2020-03-15 12:36:58.259887, fixed=MQTTFixedHeader(length=0, flags=0x0), variable=None, payload=None)`

To those above, has restarting it daily solved the problem (i.e. it occurs at some random time usually beyond one day), or does restarting frequently just reduce the frequency of failure?

**Comment by Gr3q** [comment]
I have the same problem, although I usually have to relogin to get messages again.

**Comment by Midar** [comment]
Same here. There’s usually some MQTT errors right before it happens. Maybe it makes sense to catch those and reconnect when that happens?

**Comment by Midar** [comment]
Seems this is always the last log entry when this happens:
`[2020-03-30 18:46:43,199] [WARNING@hbmqtt.client] Disconnected from broker`
Seems like disconnection is not handled by a reconnect?

**Comment by JuniorJPDJ** [comment]
Are missing messages, sent to bridge when it's during restart, caught and sent to matrix, or not? I'm considering `docker-compose restart mautrix-facebook` in cron every 6h but it takes about 2 minutes to restart on my server.

**Comment by Samonitari** [comment]
> Are missing messages, sent to bridge when it's during restart, caught and sent to matrix, or not? I'm considering `docker-compose restart mautrix-facebook` in cron every 6h but it takes about 2 minutes to restart on my server.

I'd assume no, but I never checked.
I am doing a restart exactly as you want (well, with systemd timer, but 6 hours).

**Comment by satcom886** [comment]
@JuniorJPDJ From my experience, no. After the bridge comes online, it doesn't catch up with messages posted while it was down.

**Comment by jcfj** [comment]
How about this kind of odd approach: establish two connections, restart them once every hour or so, but never at the same time? (wonder how difficult that would be to implement...)

(@JuniorJPDJ  afaik, backfilling is not implemented.)

**Comment by jcaesar** [comment]
How about this kind of odd approach: establish two connections, restart them once every hour or so, but never at the same time? (wonder how difficult that would be to implement...)

(@JuniorJPDJ afaik, backfilling is not implemented.)

**Comment by tulir** [comment]
This might be fixed with the recent fbchat update

**Comment by wvffle** [comment]
Can anyone test if it's been fixed by the fbchat update?

**Comment by matejdro** [comment]
It has been happening to me in https://github.com/tulir/mautrix-facebook/commit/56a469bf6bd1cd525cd9558e665ef11d8752f77e version. Now I'm trying https://github.com/tulir/mautrix-facebook/commit/43af3d01f1a4af6bfa9880e1f7456b52f0bc6094 and it seems good so far, but it is not enough time to tell definitely yet.

**Comment by tulir** [comment]
If it still happens, you can try `disconnect`+`connect` or `refresh` before restarting. I might add some built-in way to do those automatically if the problem still exists but is fixed by those.

**Comment by spantaleev** [comment]
I'm on the latest Docker image (`1eccf21eb294`, which likely corresponds to fcc8a69c13a14845edc).

Sometimes it would still get stuck. `ping` would tell me that it's connected, but it won't relay messages from Messenger to me. Sending messages from my side works. Sending a `refresh` command seems to fix it.

**Comment by matejdro** [comment]
I just experienced this issue again. I could send the messages, but did not receive any. I received no disconnect notification from the facebook bot and ping command reported everything is fine.

However, for me, `refresh` command just replied with  `Fatal error in listener (see logs for more info)` and did not perform actual reconnect. I had to restart bot completely to restore functionality.

Error message from logs:

```
Fatal error in listener
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 365, in try_listen
    await self.listen()
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 393, in listen
    async for event in self.listener.listen():
  File "/usr/lib/python3.8/site-packages/fbchat/_listen.py", line 379, in listen
    self._sequence_id = await fetch_sequence_id(self.session)
  File "/usr/lib/python3.8/site-packages/fbchat/_listen.py", line 93, in fetch_sequence_id
    (j,) = await session._graphql_requests(_graphql.from_doc_id("1349387578499440", params))
  File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 498, in _graphql_requests
    return await self._post("/api/graphqlbatch/", data, as_graphql=True)
  File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 467, in _post
    return _graphql.response_to_json(text)
  File "/usr/lib/python3.8/site-packages/fbchat/_graphql.py", line 49, in response_to_json
    _exception.handle_payload_error(x)
  File "/usr/lib/python3.8/site-packages/fbchat/_exception.py", line 117, in handle_payload_error
    raise error_cls(j["errorSummary"], description=j["errorDescription"], code=code)
fbchat.PleaseRefresh: #1357004 Sorry, something went wrong: Please try closing and re-opening your browser window.
```

**Comment by tulir** [comment]
[`bridge`->`periodic_reconnect`](https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/example-config.yaml#L177-L185) in the config should solve these types of issues
